// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDamPxT1hq32P8Iv1Hk4FmzTv6Eh8O29x0',
    appId: '1:913459288516:web:0ea9643faa4568c8a06c91',
    messagingSenderId: '913459288516',
    projectId: 'fir-get-to-know-flutter-8280c',
    authDomain: 'fir-get-to-know-flutter-8280c.firebaseapp.com',
    storageBucket: 'fir-get-to-know-flutter-8280c.firebasestorage.app',
    measurementId: 'G-0W2T4C7EY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBECn4bX4HuZEDKEjFl-mQvhxTki9TGApU',
    appId: '1:913459288516:android:6d54b7ab00c8719ea06c91',
    messagingSenderId: '913459288516',
    projectId: 'fir-get-to-know-flutter-8280c',
    storageBucket: 'fir-get-to-know-flutter-8280c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHi-VKPxELQcGm61eRjcEMhhhAbrKvMD8',
    appId: '1:913459288516:ios:25503de00b8d579ea06c91',
    messagingSenderId: '913459288516',
    projectId: 'fir-get-to-know-flutter-8280c',
    storageBucket: 'fir-get-to-know-flutter-8280c.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHi-VKPxELQcGm61eRjcEMhhhAbrKvMD8',
    appId: '1:913459288516:ios:25503de00b8d579ea06c91',
    messagingSenderId: '913459288516',
    projectId: 'fir-get-to-know-flutter-8280c',
    storageBucket: 'fir-get-to-know-flutter-8280c.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
